version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: orangehrm-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ../orangehrm-src
      dockerfile: ../orangehrm-dev/Dockerfile
    container_name: orangehrm-web
    restart: unless-stopped
    ports:
      - "${WEB_HTTP_PORT}:80"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - orangehrm-lib-confs:/var/www/html/lib/confs
      - orangehrm-src-cache:/var/www/html/src/cache
      - orangehrm-src-log:/var/www/html/src/log

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: orangehrm-rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_HTTP_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: orangehrm-phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_ROOT_USER}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_HTTP_PORT}:80"
    depends_on:
      - db

volumes:
  db_data:
  rabbitmq_data:
  orangehrm-lib-confs:
  orangehrm-src-cache:
  orangehrm-src-log:
